flea_1__precision_rank_11 = class ({})
flea_1__precision_rank_12 = class ({})
flea_1__precision_rank_21 = class ({})
flea_1__precision_rank_22 = class ({})
flea_1__precision_rank_31 = class ({})
flea_1__precision_rank_32 = class ({})
flea_1__precision_rank_41 = class ({})
flea_1__precision_rank_42 = class ({})

flea_2__speed_rank_11 = class ({})
flea_2__speed_rank_12 = class ({})
flea_2__speed_rank_21 = class ({})
flea_2__speed_rank_22 = class ({})
flea_2__speed_rank_31 = class ({})
flea_2__speed_rank_32 = class ({})
flea_2__speed_rank_41 = class ({})
flea_2__speed_rank_42 = class ({})

flea_3__jump_rank_11 = class ({})
flea_3__jump_rank_12 = class ({})
flea_3__jump_rank_21 = class ({})
flea_3__jump_rank_22 = class ({})
flea_3__jump_rank_31 = class ({})
flea_3__jump_rank_32 = class ({})
flea_3__jump_rank_41 = class ({})
flea_3__jump_rank_42 = class ({})

flea_4__smoke_rank_11 = class ({})
flea_4__smoke_rank_12 = class ({})
flea_4__smoke_rank_21 = class ({})
flea_4__smoke_rank_22 = class ({})
flea_4__smoke_rank_31 = class ({})
flea_4__smoke_rank_32 = class ({})
flea_4__smoke_rank_41 = class ({})
flea_4__smoke_rank_42 = class ({})

flea_5__desolator_rank_11 = class ({})
flea_5__desolator_rank_12 = class ({})
flea_5__desolator_rank_21 = class ({})
flea_5__desolator_rank_22 = class ({})
flea_5__desolator_rank_31 = class ({})
flea_5__desolator_rank_32 = class ({})
flea_5__desolator_rank_41 = class ({})
flea_5__desolator_rank_42 = class ({})

flea_u__weakness_rank_11 = class ({})
flea_u__weakness_rank_12 = class ({})
flea_u__weakness_rank_21 = class ({})
flea_u__weakness_rank_22 = class ({})
flea_u__weakness_rank_31 = class ({})
flea_u__weakness_rank_32 = class ({})
flea_u__weakness_rank_41 = class ({})
flea_u__weakness_rank_42 = class ({})

flea__precache = class ({})

function flea__precache:Spawn()
    if self:IsTrained() == false then self:UpgradeAbility(true) end
end

function flea__precache:Precache(context)
    PrecacheResource("soundfile", "soundevents/soundevent_flea.vsndevts", context)
end