flea_1__precision_rank_11 = class ({})
flea_1__precision_rank_12 = class ({})
flea_1__precision_rank_21 = class ({})
flea_1__precision_rank_22 = class ({})
flea_1__precision_rank_31 = class ({})
flea_1__precision_rank_32 = class ({})
flea_1__precision_rank_41 = class ({})
flea_1__precision_rank_42 = class ({})

flea_2__sk2_rank_11 = class ({})
flea_2__sk2_rank_12 = class ({})
flea_2__sk2_rank_21 = class ({})
flea_2__sk2_rank_22 = class ({})
flea_2__sk2_rank_31 = class ({})
flea_2__sk2_rank_32 = class ({})
flea_2__sk2_rank_41 = class ({})
flea_2__sk2_rank_42 = class ({})

flea_3__sk3_rank_11 = class ({})
flea_3__sk3_rank_12 = class ({})
flea_3__sk3_rank_21 = class ({})
flea_3__sk3_rank_22 = class ({})
flea_3__sk3_rank_31 = class ({})
flea_3__sk3_rank_32 = class ({})
flea_3__sk3_rank_41 = class ({})
flea_3__sk3_rank_42 = class ({})

flea_4__sk4_rank_11 = class ({})
flea_4__sk4_rank_12 = class ({})
flea_4__sk4_rank_21 = class ({})
flea_4__sk4_rank_22 = class ({})
flea_4__sk4_rank_31 = class ({})
flea_4__sk4_rank_32 = class ({})
flea_4__sk4_rank_41 = class ({})
flea_4__sk4_rank_42 = class ({})

flea_5__sk5_rank_11 = class ({})
flea_5__sk5_rank_12 = class ({})
flea_5__sk5_rank_21 = class ({})
flea_5__sk5_rank_22 = class ({})
flea_5__sk5_rank_31 = class ({})
flea_5__sk5_rank_32 = class ({})
flea_5__sk5_rank_41 = class ({})
flea_5__sk5_rank_42 = class ({})

flea_u__sk6_rank_11 = class ({})
flea_u__sk6_rank_12 = class ({})
flea_u__sk6_rank_21 = class ({})
flea_u__sk6_rank_22 = class ({})
flea_u__sk6_rank_31 = class ({})
flea_u__sk6_rank_32 = class ({})
flea_u__sk6_rank_41 = class ({})
flea_u__sk6_rank_42 = class ({})

flea__precache = class ({})

function flea__precache:Spawn()
    if self:IsTrained() == false then self:UpgradeAbility(true) end
end

function flea__precache:Precache(context)
    PrecacheResource("soundfile", "soundevents/soundevent_flea.vsndevts", context)
end