druid_1__root_rank_11 = class ({})
druid_1__root_rank_12 = class ({})
druid_1__root_rank_21 = class ({})
druid_1__root_rank_22 = class ({})
druid_1__root_rank_31 = class ({})
druid_1__root_rank_32 = class ({})
druid_1__root_rank_41 = class ({})
druid_1__root_rank_42 = class ({})

druid_2__sk2_rank_11 = class ({})
druid_2__sk2_rank_12 = class ({})
druid_2__sk2_rank_21 = class ({})
druid_2__sk2_rank_22 = class ({})
druid_2__sk2_rank_31 = class ({})
druid_2__sk2_rank_32 = class ({})
druid_2__sk2_rank_41 = class ({})
druid_2__sk2_rank_42 = class ({})

druid_3__totem_rank_11 = class ({})
druid_3__totem_rank_12 = class ({})
druid_3__totem_rank_21 = class ({})
druid_3__totem_rank_22 = class ({})
druid_3__totem_rank_31 = class ({})
druid_3__totem_rank_32 = class ({})
druid_3__totem_rank_41 = class ({})
druid_3__totem_rank_42 = class ({})

druid_4__sk4_rank_11 = class ({})
druid_4__sk4_rank_12 = class ({})
druid_4__sk4_rank_21 = class ({})
druid_4__sk4_rank_22 = class ({})
druid_4__sk4_rank_31 = class ({})
druid_4__sk4_rank_32 = class ({})
druid_4__sk4_rank_41 = class ({})
druid_4__sk4_rank_42 = class ({})

druid_5__sk5_rank_11 = class ({})
druid_5__sk5_rank_12 = class ({})
druid_5__sk5_rank_21 = class ({})
druid_5__sk5_rank_22 = class ({})
druid_5__sk5_rank_31 = class ({})
druid_5__sk5_rank_32 = class ({})
druid_5__sk5_rank_41 = class ({})
druid_5__sk5_rank_42 = class ({})

druid_6__entangled_rank_11 = class ({})
druid_6__entangled_rank_12 = class ({})
druid_6__entangled_rank_21 = class ({})
druid_6__entangled_rank_22 = class ({})
druid_6__entangled_rank_31 = class ({})
druid_6__entangled_rank_32 = class ({})
druid_6__entangled_rank_41 = class ({})
druid_6__entangled_rank_42 = class ({})

druid_u__sk7_rank_11 = class ({})
druid_u__sk7_rank_12 = class ({})
druid_u__sk7_rank_21 = class ({})
druid_u__sk7_rank_22 = class ({})
druid_u__sk7_rank_31 = class ({})
druid_u__sk7_rank_32 = class ({})
druid_u__sk7_rank_41 = class ({})
druid_u__sk7_rank_42 = class ({})

druid__precache = class ({})

function druid__precache:Spawn()
    if self:IsTrained() == false then self:UpgradeAbility(true) end
end

function druid__precache:Precache(context)
    PrecacheResource("soundfile", "soundevents/soundevent_druid.vsndevts", context)
end