druid_1__root_rank_11 = class ({})
druid_1__root_rank_12 = class ({})
druid_1__root_rank_21 = class ({})
druid_1__root_rank_22 = class ({})
druid_1__root_rank_31 = class ({})
druid_1__root_rank_32 = class ({})
druid_1__root_rank_41 = class ({})
druid_1__root_rank_42 = class ({})

druid_2__armor_rank_11 = class ({})
druid_2__armor_rank_12 = class ({})
druid_2__armor_rank_21 = class ({})
druid_2__armor_rank_22 = class ({})
druid_2__armor_rank_31 = class ({})
druid_2__armor_rank_32 = class ({})
druid_2__armor_rank_41 = class ({})
druid_2__armor_rank_42 = class ({})

druid_3__totem_rank_11 = class ({})
druid_3__totem_rank_12 = class ({})
druid_3__totem_rank_21 = class ({})
druid_3__totem_rank_22 = class ({})
druid_3__totem_rank_31 = class ({})
druid_3__totem_rank_32 = class ({})
druid_3__totem_rank_41 = class ({})
druid_3__totem_rank_42 = class ({})

druid_4__teleport_rank_11 = class ({})
druid_4__teleport_rank_12 = class ({})
druid_4__teleport_rank_21 = class ({})
druid_4__teleport_rank_22 = class ({})
druid_4__teleport_rank_31 = class ({})
druid_4__teleport_rank_32 = class ({})
druid_4__teleport_rank_41 = class ({})
druid_4__teleport_rank_42 = class ({})

druid_5__metamorphosis_rank_11 = class ({})
druid_5__metamorphosis_rank_12 = class ({})
druid_5__metamorphosis_rank_21 = class ({})
druid_5__metamorphosis_rank_22 = class ({})
druid_5__metamorphosis_rank_31 = class ({})
druid_5__metamorphosis_rank_32 = class ({})
druid_5__metamorphosis_rank_41 = class ({})
druid_5__metamorphosis_rank_42 = class ({})

druid_6__entangled_rank_11 = class ({})
druid_6__entangled_rank_12 = class ({})
druid_6__entangled_rank_21 = class ({})
druid_6__entangled_rank_22 = class ({})
druid_6__entangled_rank_31 = class ({})
druid_6__entangled_rank_32 = class ({})
druid_6__entangled_rank_41 = class ({})
druid_6__entangled_rank_42 = class ({})

druid_u__conversion_rank_11 = class ({})
druid_u__conversion_rank_12 = class ({})
druid_u__conversion_rank_21 = class ({})
druid_u__conversion_rank_22 = class ({})
druid_u__conversion_rank_31 = class ({})
druid_u__conversion_rank_32 = class ({})
druid_u__conversion_rank_41 = class ({})
druid_u__conversion_rank_42 = class ({})

druid__precache = class ({})

function druid__precache:Spawn()
    if self:IsTrained() == false then self:UpgradeAbility(true) end
end

function druid__precache:Precache(context)
    PrecacheResource("soundfile", "soundevents/soundevent_druid.vsndevts", context)
end