shadow_1__sk1_rank_11 = class ({})
shadow_1__sk1_rank_12 = class ({})
shadow_1__sk1_rank_21 = class ({})
shadow_1__sk1_rank_22 = class ({})
shadow_1__sk1_rank_31 = class ({})
shadow_1__sk1_rank_32 = class ({})
shadow_1__sk1_rank_41 = class ({})
shadow_1__sk1_rank_42 = class ({})

shadow_2__sk2_rank_11 = class ({})
shadow_2__sk2_rank_12 = class ({})
shadow_2__sk2_rank_21 = class ({})
shadow_2__sk2_rank_22 = class ({})
shadow_2__sk2_rank_31 = class ({})
shadow_2__sk2_rank_32 = class ({})
shadow_2__sk2_rank_41 = class ({})
shadow_2__sk2_rank_42 = class ({})

shadow_3__sk3_rank_11 = class ({})
shadow_3__sk3_rank_12 = class ({})
shadow_3__sk3_rank_21 = class ({})
shadow_3__sk3_rank_22 = class ({})
shadow_3__sk3_rank_31 = class ({})
shadow_3__sk3_rank_32 = class ({})
shadow_3__sk3_rank_41 = class ({})
shadow_3__sk3_rank_42 = class ({})

shadow_4__sk4_rank_11 = class ({})
shadow_4__sk4_rank_12 = class ({})
shadow_4__sk4_rank_21 = class ({})
shadow_4__sk4_rank_22 = class ({})
shadow_4__sk4_rank_31 = class ({})
shadow_4__sk4_rank_32 = class ({})
shadow_4__sk4_rank_41 = class ({})
shadow_4__sk4_rank_42 = class ({})

shadow_5__sk5_rank_11 = class ({})
shadow_5__sk5_rank_12 = class ({})
shadow_5__sk5_rank_21 = class ({})
shadow_5__sk5_rank_22 = class ({})
shadow_5__sk5_rank_31 = class ({})
shadow_5__sk5_rank_32 = class ({})
shadow_5__sk5_rank_41 = class ({})
shadow_5__sk5_rank_42 = class ({})

shadow_u__sk6_rank_11 = class ({})
shadow_u__sk6_rank_12 = class ({})
shadow_u__sk6_rank_21 = class ({})
shadow_u__sk6_rank_22 = class ({})
shadow_u__sk6_rank_31 = class ({})
shadow_u__sk6_rank_32 = class ({})
shadow_u__sk6_rank_41 = class ({})
shadow_u__sk6_rank_42 = class ({})

shadow__precache = class ({})

function shadow__precache:Spawn()
    if self:IsTrained() == false then self:UpgradeAbility(true) end
end

function shadow__precache:Precache(context)
    --PrecacheResource("soundfile", "soundevents/soundevent_shadow.vsndevts", context)
end