shadowmancer_1__weapon_rank_11 = class ({})
shadowmancer_1__weapon_rank_12 = class ({})
shadowmancer_1__weapon_rank_21 = class ({})
shadowmancer_1__weapon_rank_22 = class ({})
shadowmancer_1__weapon_rank_31 = class ({})
shadowmancer_1__weapon_rank_32 = class ({})
shadowmancer_1__weapon_rank_41 = class ({})
shadowmancer_1__weapon_rank_42 = class ({})

shadowmancer_2__walk_rank_11 = class ({})
shadowmancer_2__walk_rank_12 = class ({})
shadowmancer_2__walk_rank_21 = class ({})
shadowmancer_2__walk_rank_22 = class ({})
shadowmancer_2__walk_rank_31 = class ({})
shadowmancer_2__walk_rank_32 = class ({})
shadowmancer_2__walk_rank_41 = class ({})
shadowmancer_2__walk_rank_42 = class ({})

shadowmancer_3__assault_rank_11 = class ({})
shadowmancer_3__assault_rank_12 = class ({})
shadowmancer_3__assault_rank_21 = class ({})
shadowmancer_3__assault_rank_22 = class ({})
shadowmancer_3__assault_rank_31 = class ({})
shadowmancer_3__assault_rank_32 = class ({})
shadowmancer_3__assault_rank_41 = class ({})
shadowmancer_3__assault_rank_42 = class ({})

shadowmancer_4__heart_rank_11 = class ({})
shadowmancer_4__heart_rank_12 = class ({})
shadowmancer_4__heart_rank_21 = class ({})
shadowmancer_4__heart_rank_22 = class ({})
shadowmancer_4__heart_rank_31 = class ({})
shadowmancer_4__heart_rank_32 = class ({})
shadowmancer_4__heart_rank_41 = class ({})
shadowmancer_4__heart_rank_42 = class ({})

shadowmancer_5__cloud_rank_11 = class ({})
shadowmancer_5__cloud_rank_12 = class ({})
shadowmancer_5__cloud_rank_21 = class ({})
shadowmancer_5__cloud_rank_22 = class ({})
shadowmancer_5__cloud_rank_31 = class ({})
shadowmancer_5__cloud_rank_32 = class ({})
shadowmancer_5__cloud_rank_41 = class ({})
shadowmancer_5__cloud_rank_42 = class ({})

shadowmancer_u__dagger_rank_11 = class ({})
shadowmancer_u__dagger_rank_12 = class ({})
shadowmancer_u__dagger_rank_21 = class ({})
shadowmancer_u__dagger_rank_22 = class ({})
shadowmancer_u__dagger_rank_31 = class ({})
shadowmancer_u__dagger_rank_32 = class ({})
shadowmancer_u__dagger_rank_41 = class ({})
shadowmancer_u__dagger_rank_42 = class ({})

shadowmancer__precache = class ({})

function shadowmancer__precache:Spawn()
    if self:IsTrained() == false then self:UpgradeAbility(true) end
end

function shadowmancer__precache:Precache(context)
    --PrecacheResource("soundfile", "soundevents/soundevent_shadowmancer.vsndevts", context)
end