-- SHADOW
    -- SHADOW 1
        shadow_1__weapon_rank_1_1 = class ({})
        shadow_1__weapon_rank_1_2 = class ({})
        shadow_1__weapon_rank_1_3 = class ({})
        shadow_1__weapon_rank_2_1 = class ({})
        shadow_1__weapon_rank_2_2 = class ({})
        shadow_1__weapon_rank_2_3 = class ({})
        shadow_1__weapon_rank_3_1 = class ({})
        shadow_1__weapon_rank_3_2 = class ({})
        shadow_1__weapon_rank_3_3 = class ({})

    -- SHADOW 2
        shadow_2__smoke_rank_1_1 = class ({})
        shadow_2__smoke_rank_1_2 = class ({})
        shadow_2__smoke_rank_1_3 = class ({})
        shadow_2__smoke_rank_2_1 = class ({})
        shadow_2__smoke_rank_2_2 = class ({})
        shadow_2__smoke_rank_2_3 = class ({})
        shadow_2__smoke_rank_3_1 = class ({})
        shadow_2__smoke_rank_3_2 = class ({})
        shadow_2__smoke_rank_3_3 = class ({})

    -- SHADOW 3
        shadow_3__walk_rank_1_1 = class ({})
        shadow_3__walk_rank_1_2 = class ({})
        shadow_3__walk_rank_1_3 = class ({})
        shadow_3__walk_rank_2_1 = class ({})
        shadow_3__walk_rank_2_2 = class ({})
        shadow_3__walk_rank_2_3 = class ({})
        shadow_3__walk_rank_3_1 = class ({})
        shadow_3__walk_rank_3_2 = class ({})
        shadow_3__walk_rank_3_3 = class ({})

    -- SHADOW U
        shadow_u__dagger_rank_1_1 = class ({})
        shadow_u__dagger_rank_1_2 = class ({})
        shadow_u__dagger_rank_1_3 = class ({})
        shadow_u__dagger_rank_2_1 = class ({})
        shadow_u__dagger_rank_2_2 = class ({})
        shadow_u__dagger_rank_2_3 = class ({})
        shadow_u__dagger_rank_3_1 = class ({})
        shadow_u__dagger_rank_3_2 = class ({})
        shadow_u__dagger_rank_3_3 = class ({})

-- ICEBREAKER
    -- ICEBREAKER 1
        icebreaker_1__frost_rank_1_1 = class ({})
        icebreaker_1__frost_rank_1_2 = class ({})
        icebreaker_1__frost_rank_1_3 = class ({})
        icebreaker_1__frost_rank_2_1 = class ({})
        icebreaker_1__frost_rank_2_2 = class ({})
        icebreaker_1__frost_rank_2_3 = class ({})
        icebreaker_1__frost_rank_3_1 = class ({})
        icebreaker_1__frost_rank_3_2 = class ({})
        icebreaker_1__frost_rank_3_3 = class ({})

    -- ICEBREAKER 2
        icebreaker_2__discus_rank_1_1 = class ({})
        icebreaker_2__discus_rank_1_2 = class ({})
        icebreaker_2__discus_rank_1_3 = class ({})
        icebreaker_2__discus_rank_2_1 = class ({})
        icebreaker_2__discus_rank_2_2 = class ({})
        icebreaker_2__discus_rank_2_3 = class ({})
        icebreaker_2__discus_rank_3_1 = class ({})
        icebreaker_2__discus_rank_3_2 = class ({})
        icebreaker_2__discus_rank_3_3 = class ({})

    -- ICEBREAKER 3
        icebreaker_3__blink_rank_1_1 = class ({})
        icebreaker_3__blink_rank_1_2 = class ({})
        icebreaker_3__blink_rank_1_3 = class ({})
        icebreaker_3__blink_rank_2_1 = class ({})
        icebreaker_3__blink_rank_2_2 = class ({})
        icebreaker_3__blink_rank_2_3 = class ({})
        icebreaker_3__blink_rank_3_1 = class ({})
        icebreaker_3__blink_rank_3_2 = class ({})
        icebreaker_3__blink_rank_3_3 = class ({})

    -- ICEBREAKER U
        icebreaker_u__zero_rank_1_1 = class ({})
        icebreaker_u__zero_rank_1_2 = class ({})
        icebreaker_u__zero_rank_1_3 = class ({})
        icebreaker_u__zero_rank_2_1 = class ({})
        icebreaker_u__zero_rank_2_2 = class ({})
        icebreaker_u__zero_rank_2_3 = class ({})
        icebreaker_u__zero_rank_3_1 = class ({})
        icebreaker_u__zero_rank_3_2 = class ({})
        icebreaker_u__zero_rank_3_3 = class ({})

-- BOCUSE
    -- BOCUSE 1
        bocuse_1__julienne_rank_1_1 = class ({})
        bocuse_1__julienne_rank_1_2 = class ({})
        bocuse_1__julienne_rank_1_3 = class ({})
        bocuse_1__julienne_rank_2_1 = class ({})
        bocuse_1__julienne_rank_2_2 = class ({})
        bocuse_1__julienne_rank_2_3 = class ({})
        bocuse_1__julienne_rank_3_1 = class ({})
        bocuse_1__julienne_rank_3_2 = class ({})
        bocuse_1__julienne_rank_3_3 = class ({})
        bocuse_1__julienne_rank_4_1 = class ({})
        bocuse_1__julienne_rank_4_2 = class ({})

    -- BOCUSE 2
        bocuse_2__flambee_rank_1_1 = class ({})
        bocuse_2__flambee_rank_1_2 = class ({})
        bocuse_2__flambee_rank_1_3 = class ({})
        bocuse_2__flambee_rank_2_1 = class ({})
        bocuse_2__flambee_rank_2_2 = class ({})
        bocuse_2__flambee_rank_2_3 = class ({})
        bocuse_2__flambee_rank_3_1 = class ({})
        bocuse_2__flambee_rank_3_2 = class ({})
        bocuse_2__flambee_rank_3_3 = class ({})
        bocuse_2__flambee_rank_4_1 = class ({})
        bocuse_2__flambee_rank_4_2 = class ({})

    -- BOCUSE 3
        bocuse_3__sauce_rank_1_1 = class ({})
        bocuse_3__sauce_rank_1_2 = class ({})
        bocuse_3__sauce_rank_1_3 = class ({})
        bocuse_3__sauce_rank_2_1 = class ({})
        bocuse_3__sauce_rank_2_2 = class ({})
        bocuse_3__sauce_rank_2_3 = class ({})
        bocuse_3__sauce_rank_3_1 = class ({})
        bocuse_3__sauce_rank_3_2 = class ({})
        bocuse_3__sauce_rank_3_3 = class ({})
        bocuse_3__sauce_rank_4_1 = class ({})
        bocuse_3__sauce_rank_4_2 = class ({})

    -- BOCUSE U
        bocuse_u__mise_rank_1_1 = class ({})
        bocuse_u__mise_rank_1_2 = class ({})
        bocuse_u__mise_rank_1_3 = class ({})
        bocuse_u__mise_rank_2_1 = class ({})
        bocuse_u__mise_rank_2_2 = class ({})
        bocuse_u__mise_rank_2_3 = class ({})
        bocuse_u__mise_rank_3_1 = class ({})
        bocuse_u__mise_rank_3_2 = class ({})
        bocuse_u__mise_rank_3_3 = class ({})
        bocuse_u__mise_rank_4_1 = class ({})
        bocuse_u__mise_rank_4_2 = class ({})

-- INQUISITOR
    -- INQUISITOR 1
        inquisitor_1__shield_rank_1_1 = class ({})
        inquisitor_1__shield_rank_1_2 = class ({})
        inquisitor_1__shield_rank_1_3 = class ({})
        inquisitor_1__shield_rank_2_1 = class ({})
        inquisitor_1__shield_rank_2_2 = class ({})
        inquisitor_1__shield_rank_2_3 = class ({})
        inquisitor_1__shield_rank_3_1 = class ({})
        inquisitor_1__shield_rank_3_2 = class ({})
        inquisitor_1__shield_rank_3_3 = class ({})

    -- INQUISITOR 2
        inquisitor_2__portal_rank_1_1 = class ({})
        inquisitor_2__portal_rank_1_2 = class ({})
        inquisitor_2__portal_rank_1_3 = class ({})
        inquisitor_2__portal_rank_2_1 = class ({})
        inquisitor_2__portal_rank_2_2 = class ({})
        inquisitor_2__portal_rank_2_3 = class ({})
        inquisitor_2__portal_rank_3_1 = class ({})
        inquisitor_2__portal_rank_3_2 = class ({})
        inquisitor_2__portal_rank_3_3 = class ({})

    -- INQUISITOR 3
        inquisitor_3__sonicblow_rank_1_1 = class ({})
        inquisitor_3__sonicblow_rank_1_2 = class ({})
        inquisitor_3__sonicblow_rank_1_3 = class ({})
        inquisitor_3__sonicblow_rank_2_1 = class ({})
        inquisitor_3__sonicblow_rank_2_2 = class ({})
        inquisitor_3__sonicblow_rank_2_3 = class ({})
        inquisitor_3__sonicblow_rank_3_1 = class ({})
        inquisitor_3__sonicblow_rank_3_2 = class ({})
        inquisitor_3__sonicblow_rank_3_3 = class ({})

    -- INQUISITOR U
        inquisitor_u__autocast_rank_1_1 = class ({})
        inquisitor_u__autocast_rank_1_2 = class ({})
        inquisitor_u__autocast_rank_1_3 = class ({})
        inquisitor_u__autocast_rank_2_1 = class ({})
        inquisitor_u__autocast_rank_2_2 = class ({})
        inquisitor_u__autocast_rank_2_3 = class ({})
        inquisitor_u__autocast_rank_3_1 = class ({})
        inquisitor_u__autocast_rank_3_2 = class ({})
        inquisitor_u__autocast_rank_3_3 = class ({})

-- BLOODSTAINED
    -- BLOODSTAINED 1
        bloodstained_1__rage_rank_1_1 = class ({})
        bloodstained_1__rage_rank_1_2 = class ({})
        bloodstained_1__rage_rank_1_3 = class ({})
        bloodstained_1__rage_rank_2_1 = class ({})
        bloodstained_1__rage_rank_2_2 = class ({})
        bloodstained_1__rage_rank_2_3 = class ({})
        bloodstained_1__rage_rank_3_1 = class ({})
        bloodstained_1__rage_rank_3_2 = class ({})
        bloodstained_1__rage_rank_3_3 = class ({})

    -- BLOODSTAINED 2
        bloodstained_2__bloodsteal_rank_1_1 = class ({})
        bloodstained_2__bloodsteal_rank_1_2 = class ({})
        bloodstained_2__bloodsteal_rank_1_3 = class ({})
        bloodstained_2__bloodsteal_rank_2_1 = class ({})
        bloodstained_2__bloodsteal_rank_2_2 = class ({})
        bloodstained_2__bloodsteal_rank_2_3 = class ({})
        bloodstained_2__bloodsteal_rank_3_1 = class ({})
        bloodstained_2__bloodsteal_rank_3_2 = class ({})
        bloodstained_2__bloodsteal_rank_3_3 = class ({})

    -- BLOODSTAINED 3
        bloodstained_3__curse_rank_1_1 = class ({})
        bloodstained_3__curse_rank_1_2 = class ({})
        bloodstained_3__curse_rank_1_3 = class ({})
        bloodstained_3__curse_rank_2_1 = class ({})
        bloodstained_3__curse_rank_2_2 = class ({})
        bloodstained_3__curse_rank_2_3 = class ({})
        bloodstained_3__curse_rank_3_1 = class ({})
        bloodstained_3__curse_rank_3_2 = class ({})
        bloodstained_3__curse_rank_3_3 = class ({})

    -- BLOODSTAINED U
        bloodstained_u__seal_rank_1_1 = class ({})
        bloodstained_u__seal_rank_1_2 = class ({})
        bloodstained_u__seal_rank_1_3 = class ({})
        bloodstained_u__seal_rank_2_1 = class ({})
        bloodstained_u__seal_rank_2_2 = class ({})
        bloodstained_u__seal_rank_2_3 = class ({})
        bloodstained_u__seal_rank_3_1 = class ({})
        bloodstained_u__seal_rank_3_2 = class ({})
        bloodstained_u__seal_rank_3_3 = class ({})

-- CRUSADER
    -- CRUSADER 1
        crusader_1__summon_rank_1_1 = class ({})
        crusader_1__summon_rank_1_2 = class ({})
        crusader_1__summon_rank_1_3 = class ({})
        crusader_1__summon_rank_2_1 = class ({})
        crusader_1__summon_rank_2_2 = class ({})
        crusader_1__summon_rank_2_3 = class ({})
        crusader_1__summon_rank_3_1 = class ({})
        crusader_1__summon_rank_3_2 = class ({})
        crusader_1__summon_rank_3_3 = class ({})

    -- CRUSADER 2
        crusader_2__shield_rank_1_1 = class ({})
        crusader_2__shield_rank_1_2 = class ({})
        crusader_2__shield_rank_1_3 = class ({})
        crusader_2__shield_rank_2_1 = class ({})
        crusader_2__shield_rank_2_2 = class ({})
        crusader_2__shield_rank_2_3 = class ({})
        crusader_2__shield_rank_3_1 = class ({})
        crusader_2__shield_rank_3_2 = class ({})
        crusader_2__shield_rank_3_3 = class ({})

    -- CRUSADER 3
        crusader_3__counter_rank_1_1 = class ({})
        crusader_3__counter_rank_1_2 = class ({})
        crusader_3__counter_rank_1_3 = class ({})
        crusader_3__counter_rank_2_1 = class ({})
        crusader_3__counter_rank_2_2 = class ({})
        crusader_3__counter_rank_2_3 = class ({})
        crusader_3__counter_rank_3_1 = class ({})
        crusader_3__counter_rank_3_2 = class ({})
        crusader_3__counter_rank_3_3 = class ({})

    -- CRUSADER U
        crusader_u__aura_rank_1_1 = class ({})
        crusader_u__aura_rank_1_2 = class ({})
        crusader_u__aura_rank_1_3 = class ({})
        crusader_u__aura_rank_2_1 = class ({})
        crusader_u__aura_rank_2_2 = class ({})
        crusader_u__aura_rank_2_3 = class ({})
        crusader_u__aura_rank_3_1 = class ({})
        crusader_u__aura_rank_3_2 = class ({})
        crusader_u__aura_rank_3_3 = class ({})

-- DASDINGO
    -- DASDINGO 1
        dasdingo_1__heal_rank_1_1 = class ({})
        dasdingo_1__heal_rank_1_2 = class ({})
        dasdingo_1__heal_rank_1_3 = class ({})
        dasdingo_1__heal_rank_2_1 = class ({})
        dasdingo_1__heal_rank_2_2 = class ({})
        dasdingo_1__heal_rank_2_3 = class ({})
        dasdingo_1__heal_rank_3_1 = class ({})
        dasdingo_1__heal_rank_3_2 = class ({})
        dasdingo_1__heal_rank_3_3 = class ({})

    -- DASDINGO 2
        dasdingo_2__aura_rank_1_1 = class ({})
        dasdingo_2__aura_rank_1_2 = class ({})
        dasdingo_2__aura_rank_1_3 = class ({})
        dasdingo_2__aura_rank_2_1 = class ({})
        dasdingo_2__aura_rank_2_2 = class ({})
        dasdingo_2__aura_rank_2_3 = class ({})
        dasdingo_2__aura_rank_3_1 = class ({})
        dasdingo_2__aura_rank_3_2 = class ({})
        dasdingo_2__aura_rank_3_3 = class ({})

    -- DASDINGO 3
        dasdingo_3__hex_rank_1_1 = class ({})
        dasdingo_3__hex_rank_1_2 = class ({})
        dasdingo_3__hex_rank_1_3 = class ({})
        dasdingo_3__hex_rank_2_1 = class ({})
        dasdingo_3__hex_rank_2_2 = class ({})
        dasdingo_3__hex_rank_2_3 = class ({})
        dasdingo_3__hex_rank_3_1 = class ({})
        dasdingo_3__hex_rank_3_2 = class ({})
        dasdingo_3__hex_rank_3_3 = class ({})

    -- DASDINGO U
        dasdingo_u__maledict_rank_1_1 = class ({})
        dasdingo_u__maledict_rank_1_2 = class ({})
        dasdingo_u__maledict_rank_1_3 = class ({})
        dasdingo_u__maledict_rank_2_1 = class ({})
        dasdingo_u__maledict_rank_2_2 = class ({})
        dasdingo_u__maledict_rank_2_3 = class ({})
        dasdingo_u__maledict_rank_3_1 = class ({})
        dasdingo_u__maledict_rank_3_2 = class ({})
        dasdingo_u__maledict_rank_3_3 = class ({})

-- DRUID
    -- DRUID 1
        druid_1__conversion_rank_1_1 = class ({})
        druid_1__conversion_rank_1_2 = class ({})
        druid_1__conversion_rank_1_3 = class ({})
        druid_1__conversion_rank_2_1 = class ({})
        druid_1__conversion_rank_2_2 = class ({})
        druid_1__conversion_rank_2_3 = class ({})
        druid_1__conversion_rank_3_1 = class ({})
        druid_1__conversion_rank_3_2 = class ({})
        druid_1__conversion_rank_3_3 = class ({})
        druid_1__conversion_rank_4_1 = class ({})
        druid_1__conversion_rank_4_2 = class ({})

    -- DRUID 2
        druid_2__root_rank_1_1 = class ({})
        druid_2__root_rank_1_2 = class ({})
        druid_2__root_rank_1_3 = class ({})
        druid_2__root_rank_2_1 = class ({})
        druid_2__root_rank_2_2 = class ({})
        druid_2__root_rank_2_3 = class ({})
        druid_2__root_rank_3_1 = class ({})
        druid_2__root_rank_3_2 = class ({})
        druid_2__root_rank_4_1 = class ({})
        druid_2__root_rank_4_2 = class ({})

    -- DRUID 3
        druid_3__totem_rank_1_1 = class ({})
        druid_3__totem_rank_1_2 = class ({})
        druid_3__totem_rank_1_3 = class ({})
        druid_3__totem_rank_2_1 = class ({})
        druid_3__totem_rank_2_2 = class ({})
        druid_3__totem_rank_2_3 = class ({})
        druid_3__totem_rank_3_1 = class ({})
        druid_3__totem_rank_3_2 = class ({})
        druid_3__totem_rank_3_3 = class ({})
        druid_3__totem_rank_4_1 = class ({})
        druid_3__totem_rank_4_2 = class ({})


    -- DRUID U
        druid_u__seed_rank_1_1 = class ({})
        druid_u__seed_rank_1_2 = class ({})
        druid_u__seed_rank_1_3 = class ({})
        druid_u__seed_rank_2_1 = class ({})
        druid_u__seed_rank_2_2 = class ({})
        druid_u__seed_rank_2_3 = class ({})
        druid_u__seed_rank_3_1 = class ({})
        druid_u__seed_rank_3_2 = class ({})
        druid_u__seed_rank_3_3 = class ({})
        druid_u__seed_rank_4_1 = class ({})
        druid_u__seed_rank_4_2 = class ({})

-- STRIDER
    -- STRIDER 1
        strider_1__push_rank_1_1 = class ({})
        strider_1__push_rank_1_2 = class ({})
        strider_1__push_rank_1_3 = class ({})
        strider_1__push_rank_2_1 = class ({})
        strider_1__push_rank_2_2 = class ({})
        strider_1__push_rank_2_3 = class ({})
        strider_1__push_rank_3_1 = class ({})
        strider_1__push_rank_3_2 = class ({})
        strider_1__push_rank_3_3 = class ({})

    -- STRIDER 2
        strider_2__dash_rank_1_1 = class ({})
        strider_2__dash_rank_1_2 = class ({})
        strider_2__dash_rank_1_3 = class ({})
        strider_2__dash_rank_2_1 = class ({})
        strider_2__dash_rank_2_2 = class ({})
        strider_2__dash_rank_2_3 = class ({})
        strider_2__dash_rank_3_1 = class ({})
        strider_2__dash_rank_3_2 = class ({})
        strider_2__dash_rank_3_3 = class ({})

    -- STRIDER 3
        strider_3__wall_rank_1_1 = class ({})
        strider_3__wall_rank_1_2 = class ({})
        strider_3__wall_rank_1_3 = class ({})
        strider_3__wall_rank_2_1 = class ({})
        strider_3__wall_rank_2_2 = class ({})
        strider_3__wall_rank_2_3 = class ({})
        strider_3__wall_rank_3_1 = class ({})
        strider_3__wall_rank_3_2 = class ({})
        strider_3__wall_rank_3_3 = class ({})

    -- STRIDER U
        strider_u__spirit_rank_1_1 = class ({})
        strider_u__spirit_rank_1_2 = class ({})
        strider_u__spirit_rank_1_3 = class ({})
        strider_u__spirit_rank_2_1 = class ({})
        strider_u__spirit_rank_2_2 = class ({})
        strider_u__spirit_rank_2_3 = class ({})
        strider_u__spirit_rank_3_1 = class ({})
        strider_u__spirit_rank_3_2 = class ({})
        strider_u__spirit_rank_3_3 = class ({})

-- SLAYER
    -- SLAYER 1
        slayer_1__chain_rank_1_1 = class ({})
        slayer_1__chain_rank_1_2 = class ({})
        slayer_1__chain_rank_1_3 = class ({})
        slayer_1__chain_rank_2_1 = class ({})
        slayer_1__chain_rank_2_2 = class ({})
        slayer_1__chain_rank_2_3 = class ({})
        slayer_1__chain_rank_3_1 = class ({})
        slayer_1__chain_rank_3_2 = class ({})
        slayer_1__chain_rank_3_3 = class ({})

    -- SLAYER 2
        slayer_2__shackles_rank_1_1 = class ({})
        slayer_2__shackles_rank_1_2 = class ({})
        slayer_2__shackles_rank_1_3 = class ({})
        slayer_2__shackles_rank_2_1 = class ({})
        slayer_2__shackles_rank_2_2 = class ({})
        slayer_2__shackles_rank_2_3 = class ({})
        slayer_2__shackles_rank_3_1 = class ({})
        slayer_2__shackles_rank_3_2 = class ({})
        slayer_2__shackles_rank_3_3 = class ({})

    -- SLAYER 3
        slayer_3__vest_rank_1_1 = class ({})
        slayer_3__vest_rank_1_2 = class ({})
        slayer_3__vest_rank_1_3 = class ({})
        slayer_3__vest_rank_2_1 = class ({})
        slayer_3__vest_rank_2_2 = class ({})
        slayer_3__vest_rank_2_3 = class ({})
        slayer_3__vest_rank_3_1 = class ({})
        slayer_3__vest_rank_3_2 = class ({})
        slayer_3__vest_rank_3_3 = class ({})

    -- SLAYER U
        slayer_u__judge_rank_1_1 = class ({})
        slayer_u__judge_rank_1_2 = class ({})
        slayer_u__judge_rank_1_3 = class ({})
        slayer_u__judge_rank_2_1 = class ({})
        slayer_u__judge_rank_2_2 = class ({})
        slayer_u__judge_rank_2_3 = class ({})
        slayer_u__judge_rank_3_1 = class ({})
        slayer_u__judge_rank_3_2 = class ({})
        slayer_u__judge_rank_3_3 = class ({})

-- ATHENA
    -- ATHENA 1
        athena_1__chain_rank_1_1 = class ({})
        athena_1__chain_rank_1_2 = class ({})
        athena_1__chain_rank_1_3 = class ({})
        athena_1__chain_rank_2_1 = class ({})
        athena_1__chain_rank_2_2 = class ({})
        athena_1__chain_rank_2_3 = class ({})
        athena_1__chain_rank_3_1 = class ({})
        athena_1__chain_rank_3_2 = class ({})
        athena_1__chain_rank_3_3 = class ({})

    -- ATHENA 2
        athena_2__thunder_rank_1_1 = class ({})
        athena_2__thunder_rank_1_2 = class ({})
        athena_2__thunder_rank_1_3 = class ({})
        athena_2__thunder_rank_2_1 = class ({})
        athena_2__thunder_rank_2_2 = class ({})
        athena_2__thunder_rank_2_3 = class ({})
        athena_2__thunder_rank_3_1 = class ({})
        athena_2__thunder_rank_3_2 = class ({})
        athena_2__thunder_rank_3_3 = class ({})

    -- ATHENA 3
        athena_3__barrier_rank_1_1 = class ({})
        athena_3__barrier_rank_1_2 = class ({})
        athena_3__barrier_rank_1_3 = class ({})
        athena_3__barrier_rank_2_1 = class ({})
        athena_3__barrier_rank_2_2 = class ({})
        athena_3__barrier_rank_2_3 = class ({})
        athena_3__barrier_rank_3_1 = class ({})
        athena_3__barrier_rank_3_2 = class ({})
        athena_3__barrier_rank_3_3 = class ({})

    -- ATHENA U
        athena_u__nova_rank_1_1 = class ({})
        athena_u__nova_rank_1_2 = class ({})
        athena_u__nova_rank_1_3 = class ({})
        athena_u__nova_rank_2_1 = class ({})
        athena_u__nova_rank_2_2 = class ({})
        athena_u__nova_rank_2_3 = class ({})
        athena_u__nova_rank_3_1 = class ({})
        athena_u__nova_rank_3_2 = class ({})
        athena_u__nova_rank_3_3 = class ({})

-- BLOODMAGE
    -- BLOODMAGE 1
        bloodmage_1__book_offensive_rank_1_1 = class ({})
        bloodmage_1__book_offensive_rank_1_2 = class ({})
        bloodmage_1__book_offensive_rank_1_3 = class ({})
        bloodmage_1__book_offensive_rank_2_1 = class ({})
        bloodmage_1__book_offensive_rank_2_2 = class ({})
        bloodmage_1__book_offensive_rank_2_3 = class ({})
        bloodmage_1__book_offensive_rank_3_1 = class ({})
        bloodmage_1__book_offensive_rank_3_2 = class ({})
        bloodmage_1__book_offensive_rank_3_3 = class ({})

    -- BLOODMAGE 2
        bloodmage_2__book_buff_rank_1_1 = class ({})
        bloodmage_2__book_buff_rank_1_2 = class ({})
        bloodmage_2__book_buff_rank_1_3 = class ({})
        bloodmage_2__book_buff_rank_2_1 = class ({})
        bloodmage_2__book_buff_rank_2_2 = class ({})
        bloodmage_2__book_buff_rank_2_3 = class ({})
        bloodmage_2__book_buff_rank_3_1 = class ({})
        bloodmage_2__book_buff_rank_3_2 = class ({})
        bloodmage_2__book_buff_rank_3_3 = class ({})

    -- BLOODMAGE 3
        bloodmage_3__book_aura_rank_1_1 = class ({})
        bloodmage_3__book_aura_rank_1_2 = class ({})
        bloodmage_3__book_aura_rank_1_3 = class ({})
        bloodmage_3__book_aura_rank_2_1 = class ({})
        bloodmage_3__book_aura_rank_2_2 = class ({})
        bloodmage_3__book_aura_rank_2_3 = class ({})
        bloodmage_3__book_aura_rank_3_1 = class ({})
        bloodmage_3__book_aura_rank_3_2 = class ({})
        bloodmage_3__book_aura_rank_3_3 = class ({})

    -- BLOODMAGE 0
        bloodmage_0__sacrifice_rank_1_1 = class ({})
        bloodmage_0__sacrifice_rank_1_2 = class ({})
        bloodmage_0__sacrifice_rank_1_3 = class ({})
        bloodmage_0__sacrifice_rank_2_1 = class ({})
        bloodmage_0__sacrifice_rank_2_2 = class ({})
        bloodmage_0__sacrifice_rank_2_3 = class ({})
        bloodmage_0__sacrifice_rank_3_1 = class ({})
        bloodmage_0__sacrifice_rank_3_2 = class ({})
        bloodmage_0__sacrifice_rank_3_3 = class ({})