striker_1__blow_rank_11 = class ({})
striker_1__blow_rank_12 = class ({})
striker_1__blow_rank_21 = class ({})
striker_1__blow_rank_22 = class ({})
striker_1__blow_rank_31 = class ({})
striker_1__blow_rank_32 = class ({})
striker_1__blow_rank_41 = class ({})
striker_1__blow_rank_42 = class ({})

striker_2__shield_rank_11 = class ({})
striker_2__shield_rank_12 = class ({})
striker_2__shield_rank_21 = class ({})
striker_2__shield_rank_22 = class ({})
striker_2__shield_rank_31 = class ({})
striker_2__shield_rank_32 = class ({})
striker_2__shield_rank_41 = class ({})
striker_2__shield_rank_42 = class ({})

striker_3__portal_rank_11 = class ({})
striker_3__portal_rank_12 = class ({})
striker_3__portal_rank_21 = class ({})
striker_3__portal_rank_22 = class ({})
striker_3__portal_rank_31 = class ({})
striker_3__portal_rank_32 = class ({})
striker_3__portal_rank_41 = class ({})
striker_3__portal_rank_42 = class ({})

striker_4__hammer_rank_11 = class ({})
striker_4__hammer_rank_12 = class ({})
striker_4__hammer_rank_21 = class ({})
striker_4__hammer_rank_22 = class ({})
striker_4__hammer_rank_31 = class ({})
striker_4__hammer_rank_32 = class ({})
striker_4__hammer_rank_41 = class ({})
striker_4__hammer_rank_42 = class ({})

striker_5__clone_rank_11 = class ({})
striker_5__clone_rank_12 = class ({})
striker_5__clone_rank_21 = class ({})
striker_5__clone_rank_22 = class ({})
striker_5__clone_rank_31 = class ({})
striker_5__clone_rank_32 = class ({})
striker_5__clone_rank_41 = class ({})
striker_5__clone_rank_42 = class ({})

striker_6__tremor_rank_11 = class ({})
striker_6__tremor_rank_12 = class ({})
striker_6__tremor_rank_21 = class ({})
striker_6__tremor_rank_22 = class ({})
striker_6__tremor_rank_31 = class ({})
striker_6__tremor_rank_32 = class ({})
striker_6__tremor_rank_41 = class ({})
striker_6__tremor_rank_42 = class ({})

striker_u__auto_rank_11 = class ({})
striker_u__auto_rank_12 = class ({})
striker_u__auto_rank_21 = class ({})
striker_u__auto_rank_22 = class ({})
striker_u__auto_rank_31 = class ({})
striker_u__auto_rank_32 = class ({})
striker_u__auto_rank_41 = class ({})
striker_u__auto_rank_42 = class ({})

striker__precache = class ({})

function striker__precache:Spawn()
    if self:IsTrained() == false then self:UpgradeAbility(true) end
end

function striker__precache:Precache(context)
    --PrecacheResource("soundfile", "soundevents/soundevent_striker.vsndevts", context)
end