bocuse_1__cut_rank_11 = class ({})
bocuse_1__cut_rank_12 = class ({})
bocuse_1__cut_rank_21 = class ({})
bocuse_1__cut_rank_22 = class ({})
bocuse_1__cut_rank_31 = class ({})
bocuse_1__cut_rank_32 = class ({})
bocuse_1__cut_rank_41 = class ({})
bocuse_1__cut_rank_42 = class ({})

bocuse_2__flask_rank_11 = class ({})
bocuse_2__flask_rank_12 = class ({})
bocuse_2__flask_rank_21 = class ({})
bocuse_2__flask_rank_22 = class ({})
bocuse_2__flask_rank_31 = class ({})
bocuse_2__flask_rank_32 = class ({})
bocuse_2__flask_rank_41 = class ({})
bocuse_2__flask_rank_42 = class ({})

bocuse_3__mark_rank_11 = class ({})
bocuse_3__mark_rank_12 = class ({})
bocuse_3__mark_rank_21 = class ({})
bocuse_3__mark_rank_22 = class ({})
bocuse_3__mark_rank_31 = class ({})
bocuse_3__mark_rank_32 = class ({})
bocuse_3__mark_rank_41 = class ({})
bocuse_3__mark_rank_42 = class ({})

bocuse_4__enhance_rank_11 = class ({})
bocuse_4__enhance_rank_12 = class ({})
bocuse_4__enhance_rank_21 = class ({})
bocuse_4__enhance_rank_22 = class ({})
bocuse_4__enhance_rank_31 = class ({})
bocuse_4__enhance_rank_32 = class ({})
bocuse_4__enhance_rank_41 = class ({})
bocuse_4__enhance_rank_42 = class ({})

bocuse_5__puddle_rank_11 = class ({})
bocuse_5__puddle_rank_12 = class ({})
bocuse_5__puddle_rank_21 = class ({})
bocuse_5__puddle_rank_22 = class ({})
bocuse_5__puddle_rank_31 = class ({})
bocuse_5__puddle_rank_32 = class ({})
bocuse_5__puddle_rank_41 = class ({})
bocuse_5__puddle_rank_42 = class ({})

bocuse_6__triad_rank_11 = class ({})
bocuse_6__triad_rank_12 = class ({})
bocuse_6__triad_rank_21 = class ({})
bocuse_6__triad_rank_22 = class ({})
bocuse_6__triad_rank_31 = class ({})
bocuse_6__triad_rank_32 = class ({})
bocuse_6__triad_rank_41 = class ({})
bocuse_6__triad_rank_42 = class ({})

bocuse_u__rage_rank_11 = class ({})
bocuse_u__rage_rank_12 = class ({})
bocuse_u__rage_rank_21 = class ({})
bocuse_u__rage_rank_22 = class ({})
bocuse_u__rage_rank_31 = class ({})
bocuse_u__rage_rank_32 = class ({})
bocuse_u__rage_rank_41 = class ({})
bocuse_u__rage_rank_42 = class ({})

bocuse__precache = class ({})

function bocuse__precache:Spawn()
    if self:IsTrained() == false then self:UpgradeAbility(true) end
end

function bocuse__precache:Precache(context)
    --PrecacheResource("soundfile", "soundevents/soundevent_bocuse.vsndevts", context)
end