osiris_1__sk1_rank_11 = class ({})
osiris_1__sk1_rank_12 = class ({})
osiris_1__sk1_rank_21 = class ({})
osiris_1__sk1_rank_22 = class ({})
osiris_1__sk1_rank_31 = class ({})
osiris_1__sk1_rank_32 = class ({})
osiris_1__sk1_rank_41 = class ({})
osiris_1__sk1_rank_42 = class ({})

osiris_2__sk2_rank_11 = class ({})
osiris_2__sk2_rank_12 = class ({})
osiris_2__sk2_rank_21 = class ({})
osiris_2__sk2_rank_22 = class ({})
osiris_2__sk2_rank_31 = class ({})
osiris_2__sk2_rank_32 = class ({})
osiris_2__sk2_rank_41 = class ({})
osiris_2__sk2_rank_42 = class ({})

osiris_3__sk3_rank_11 = class ({})
osiris_3__sk3_rank_12 = class ({})
osiris_3__sk3_rank_21 = class ({})
osiris_3__sk3_rank_22 = class ({})
osiris_3__sk3_rank_31 = class ({})
osiris_3__sk3_rank_32 = class ({})
osiris_3__sk3_rank_41 = class ({})
osiris_3__sk3_rank_42 = class ({})

osiris_4__sk4_rank_11 = class ({})
osiris_4__sk4_rank_12 = class ({})
osiris_4__sk4_rank_21 = class ({})
osiris_4__sk4_rank_22 = class ({})
osiris_4__sk4_rank_31 = class ({})
osiris_4__sk4_rank_32 = class ({})
osiris_4__sk4_rank_41 = class ({})
osiris_4__sk4_rank_42 = class ({})

osiris_5__sk5_rank_11 = class ({})
osiris_5__sk5_rank_12 = class ({})
osiris_5__sk5_rank_21 = class ({})
osiris_5__sk5_rank_22 = class ({})
osiris_5__sk5_rank_31 = class ({})
osiris_5__sk5_rank_32 = class ({})
osiris_5__sk5_rank_41 = class ({})
osiris_5__sk5_rank_42 = class ({})

osiris_u__sk6_rank_11 = class ({})
osiris_u__sk6_rank_12 = class ({})
osiris_u__sk6_rank_21 = class ({})
osiris_u__sk6_rank_22 = class ({})
osiris_u__sk6_rank_31 = class ({})
osiris_u__sk6_rank_32 = class ({})
osiris_u__sk6_rank_41 = class ({})
osiris_u__sk6_rank_42 = class ({})

osiris__precache = class ({})

function osiris__precache:Spawn()
    if self:IsTrained() == false then self:UpgradeAbility(true) end
end

function osiris__precache:Precache(context)
    --PrecacheResource("soundfile", "soundevents/soundevent_osiris.vsndevts", context)
end